#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace MODEL
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MODEL.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MODEL.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<MODEL.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MODEL.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MODEL.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<MODEL.Contact>();
			}
		}
	}
}
#pragma warning restore CS1591
